#! /bin/bash

CORE_URL='https://raw.githubusercontent.com/Sunmxt/AutoDnsmasq/master/list2dnsmasq'

show_help() {
    echo -e "Usage: $0 <command>"
    echo -e ""
    echo -e "command:"
    echo -e "   install                     Install services."
    echo -e "   uninstall                   Remove AutoDnsmasq services."
    echo -e ""
    echo -e "   set-config      <file>      Set dnsmasq configure file."
    echo -e "   set-rules-id    <id>        Set rules id."
    echo -e "   set-ipset       <ipset>     Set target ipset."
    echo -e "   update                      Update right away."
    echo -e "   log                         Show log"
    echo -e "   check                       check services"
}

check_exist() {
    __result_to=$1
    while [ $1 ]
    do
        shift 1
        __path=$(whereis $1 | cut -d ':' -f 2 -) 
        __path=${__path-}
        if [ "$__path" != "" ]; then
            eval $__result_to=$1
            return 0
        fi
    done
    
    return 1
}

echo_red() {
    _string='\033[31m'$1'\033[0m'
    shift 1
    echo $_string $*
}

check_depdndencies() {
    if [ $REQUIRE_DOWNLOAD ]; then
        echo -n "checking download tools... " >&2
        check_exist __result wget curl || ( echo -e "no" >&2; return 2)
        echo -e "$__result" >&2
        _do_download=$__result
    fi

    echo -n "checking dnsmasq... " >&2
    check_exist __result dnsmasq || {
         echo -e "no" >&2
         echo -e "Dnsmasq missing."
         return 2
    }
    echo -e "yes" >&2
}

get_resource() {
    _save_to=$1
    _from=$2
    case $_do_download in 
        wget)
            wget "$_from" -O "$_save_to" || return $?
        ;;

        curl)
            curl --url "$_from" -o "$_save_to" || return $?
        ;;
    esac
}

adns_install() {
    if [ "$(whoami)" != "root" ]; then
        echo -e "Please run as root."
        return 1
    fi

    if [ -e /usr/sbin/auto_dnsmasq ]; then
        echo -e "AutoDnsmasq already installed."
        return 0
    fi
    
    REQUIRE_DOWNLOAD=1
    check_depdndencies || return $?
    
    _core_tmp=/tmp/list2dnsmasq
    get_resource "$_core_tmp" "$CORE_URL" || {
        echo -e "Cannot get list2dnsmasq." >&2
        return 2
    }

    cp -f "$0" /usr/sbin/auto_dnsmasq || {
        echo -e "Error occurs when install /usr/sbin/auto_dnsmasq"
        return 3
    }
    
    mv -f $_core_tmp /usr/sbin/list2dnsmasq || {
        echo -e "Error occurs when install /usr/sbin/list2dnsmasq"
        return 3
    }
    
    echo "Ininitialize..."
     /usr/sbin/auto_dnsmasq check
}

echo -e "AutoDnsmasq Commander"
echo -e ""

case $1 in
    install)
        shift 1
        adns_install $*
        exit $?
    ;;

    uninstall)
    ;;
    
    set-config)
    ;;
    
    set-rules-id)
    ;;

    set-ipset)
    ;;

    update)
    ;;

    log)
    ;;
esac
